package com.scau.mis.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("color", "id", Color.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("inventory", "id", Inventory.class);
		arp.addMapping("member", "id", Member.class);
		arp.addMapping("payment", "id", Payment.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("role_permission", "id", RolePermission.class);
		arp.addMapping("sale_order", "id", SaleOrder.class);
		arp.addMapping("sale_order_item", "id", SaleOrderItem.class);
		arp.addMapping("sale_reject_order", "id", SaleRejectOrder.class);
		arp.addMapping("sale_reject_order_item", "id", SaleRejectOrderItem.class);
		arp.addMapping("shop", "id", Shop.class);
		arp.addMapping("size", "id", Size.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_role", "id", UserRole.class);
		arp.addMapping("warehouse", "id", Warehouse.class);
	}
}

