package com.scau.mis.model;

import com.scau.mis.model.base.BaseBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand();
}
