package com.scau.mis.model;

import com.scau.mis.model.base.BaseColor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Color extends BaseColor<Color> {
	public static final Color dao = new Color();
}
