package com.scau.mis.model;

import com.scau.mis.model.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();
}
