package com.scau.mis.model;

import com.scau.mis.model.base.BaseInventory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inventory extends BaseInventory<Inventory> {
	public static final Inventory dao = new Inventory();
}
