package com.scau.mis.model;

import com.scau.mis.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final RolePermission dao = new RolePermission();
}
