package com.scau.mis.model;

import com.scau.mis.model.base.BaseSaleOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleOrderItem extends BaseSaleOrderItem<SaleOrderItem> {
	public static final SaleOrderItem dao = new SaleOrderItem();
}
