package com.scau.mis.model;

import com.scau.mis.model.base.BaseSaleOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleOrder extends BaseSaleOrder<SaleOrder> {
	public static final SaleOrder dao = new SaleOrder();
}
