package com.scau.mis.model;

import com.scau.mis.model.base.BaseSales;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sales extends BaseSales<Sales> {
	public static final Sales dao = new Sales();
}
