package com.scau.mis.model;

import com.scau.mis.model.base.BaseSaleRejectOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleRejectOrder extends BaseSaleRejectOrder<SaleRejectOrder> {
	public static final SaleRejectOrder dao = new SaleRejectOrder();
}
