package com.scau.mis.model;

import com.scau.mis.model.base.BaseSaleRejectOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleRejectOrderItem extends BaseSaleRejectOrderItem<SaleRejectOrderItem> {
	public static final SaleRejectOrderItem dao = new SaleRejectOrderItem();
}
