package com.scau.mis.model;

import com.scau.mis.model.base.BaseSize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Size extends BaseSize<Size> {
	public static final Size dao = new Size();
}
