package com.scau.mis.model;

import com.scau.mis.model.base.BaseStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Style extends BaseStyle<Style> {
	public static final Style dao = new Style();
}
