package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCategoryId(java.lang.Long categoryId) {
		set("categoryId", categoryId);
	}

	public java.lang.Long getCategoryId() {
		return get("categoryId");
	}

	public void setColorId(java.lang.Long colorId) {
		set("colorId", colorId);
	}

	public java.lang.Long getColorId() {
		return get("colorId");
	}

	public void setBrandId(java.lang.Long brandId) {
		set("brandId", brandId);
	}

	public java.lang.Long getBrandId() {
		return get("brandId");
	}

	public void setSizeId(java.lang.Long sizeId) {
		set("sizeId", sizeId);
	}

	public java.lang.Long getSizeId() {
		return get("sizeId");
	}

	public void setBarcode(java.lang.String barcode) {
		set("barcode", barcode);
	}

	public java.lang.String getBarcode() {
		return get("barcode");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setScript(java.lang.String script) {
		set("script", script);
	}

	public java.lang.String getScript() {
		return get("script");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
