package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStyle<M extends BaseStyle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSizeId(java.lang.Long sizeId) {
		set("sizeId", sizeId);
	}

	public java.lang.Long getSizeId() {
		return get("sizeId");
	}

	public void setBrandId(java.lang.Long brandId) {
		set("brandId", brandId);
	}

	public java.lang.Long getBrandId() {
		return get("brandId");
	}

	public void setCategoryId(java.lang.Long categoryId) {
		set("categoryId", categoryId);
	}

	public java.lang.Long getCategoryId() {
		return get("categoryId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setScript(java.lang.String script) {
		set("script", script);
	}

	public java.lang.String getScript() {
		return get("script");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
