package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSales<M extends BaseSales<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setShopId(java.lang.Long shopId) {
		set("shopId", shopId);
	}

	public java.lang.Long getShopId() {
		return get("shopId");
	}

	public void setGoodsId(java.lang.Long goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Long getGoodsId() {
		return get("goodsId");
	}

	public void setOperatorId(java.lang.Long operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.Long getOperatorId() {
		return get("operatorId");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public void setSalesAmount(java.math.BigDecimal salesAmount) {
		set("salesAmount", salesAmount);
	}

	public java.math.BigDecimal getSalesAmount() {
		return get("salesAmount");
	}

	public void setScript(java.lang.String script) {
		set("script", script);
	}

	public java.lang.String getScript() {
		return get("script");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
