package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSaleRejectOrderItem<M extends BaseSaleRejectOrderItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setRejectNo(java.lang.String rejectNo) {
		set("rejectNo", rejectNo);
	}

	public java.lang.String getRejectNo() {
		return get("rejectNo");
	}

	public void setItemId(java.lang.String itemId) {
		set("itemId", itemId);
	}

	public java.lang.String getItemId() {
		return get("itemId");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public void setRejectPrice(java.math.BigDecimal rejectPrice) {
		set("rejectPrice", rejectPrice);
	}

	public java.math.BigDecimal getRejectPrice() {
		return get("rejectPrice");
	}

	public void setSubTotal(java.math.BigDecimal subTotal) {
		set("subTotal", subTotal);
	}

	public java.math.BigDecimal getSubTotal() {
		return get("subTotal");
	}

	public void setRejectReason(java.lang.String rejectReason) {
		set("rejectReason", rejectReason);
	}

	public java.lang.String getRejectReason() {
		return get("rejectReason");
	}

}
