package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSaleRejectOrder<M extends BaseSaleRejectOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setRejectNo(java.lang.String rejectNo) {
		set("rejectNo", rejectNo);
	}

	public java.lang.String getRejectNo() {
		return get("rejectNo");
	}

	public void setRejectOrderNo(java.lang.String rejectOrderNo) {
		set("rejectOrderNo", rejectOrderNo);
	}

	public java.lang.String getRejectOrderNo() {
		return get("rejectOrderNo");
	}

	public void setRejectDateTime(java.util.Date rejectDateTime) {
		set("rejectDateTime", rejectDateTime);
	}

	public java.util.Date getRejectDateTime() {
		return get("rejectDateTime");
	}

	public void setTotal(java.math.BigDecimal total) {
		set("total", total);
	}

	public java.math.BigDecimal getTotal() {
		return get("total");
	}

	public void setOperatorId(java.lang.Long operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.Long getOperatorId() {
		return get("operatorId");
	}

	public void setShopId(java.lang.Long shopId) {
		set("shopId", shopId);
	}

	public java.lang.Long getShopId() {
		return get("shopId");
	}

}
