package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayment<M extends BasePayment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setPaymentNo(java.lang.String paymentNo) {
		set("paymentNo", paymentNo);
	}

	public java.lang.String getPaymentNo() {
		return get("paymentNo");
	}

	public void setSaleOrderNo(java.lang.String saleOrderNo) {
		set("saleOrderNo", saleOrderNo);
	}

	public java.lang.String getSaleOrderNo() {
		return get("saleOrderNo");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

	public void setPayTransactionNo(java.lang.String payTransactionNo) {
		set("payTransactionNo", payTransactionNo);
	}

	public java.lang.String getPayTransactionNo() {
		return get("payTransactionNo");
	}

	public void setPayDateTime(java.util.Date payDateTime) {
		set("payDateTime", payDateTime);
	}

	public java.util.Date getPayDateTime() {
		return get("payDateTime");
	}

	public void setOperatorId(java.lang.Long operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.Long getOperatorId() {
		return get("operatorId");
	}

	public void setShopId(java.lang.Long shopId) {
		set("shopId", shopId);
	}

	public java.lang.Long getShopId() {
		return get("shopId");
	}

}
