package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setRoleId(java.math.BigInteger roleId) {
		set("roleId", roleId);
	}

	public java.math.BigInteger getRoleId() {
		return get("roleId");
	}

	public void setPermissionId(java.math.BigInteger permissionId) {
		set("permissionId", permissionId);
	}

	public java.math.BigInteger getPermissionId() {
		return get("permissionId");
	}

}
