package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSaleOrderItem<M extends BaseSaleOrderItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSaleOrderNo(java.lang.String saleOrderNo) {
		set("saleOrderNo", saleOrderNo);
	}

	public java.lang.String getSaleOrderNo() {
		return get("saleOrderNo");
	}

	public void setItemId(java.lang.String itemId) {
		set("itemId", itemId);
	}

	public java.lang.String getItemId() {
		return get("itemId");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public void setSalePrice(java.math.BigDecimal salePrice) {
		set("salePrice", salePrice);
	}

	public java.math.BigDecimal getSalePrice() {
		return get("salePrice");
	}

	public void setSubTotal(java.math.BigDecimal subTotal) {
		set("subTotal", subTotal);
	}

	public java.math.BigDecimal getSubTotal() {
		return get("subTotal");
	}

}
