package com.scau.mis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSaleOrder<M extends BaseSaleOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSaleOrderNo(java.lang.String saleOrderNo) {
		set("saleOrderNo", saleOrderNo);
	}

	public java.lang.String getSaleOrderNo() {
		return get("saleOrderNo");
	}

	public void setCustomerNo(java.lang.String customerNo) {
		set("customerNo", customerNo);
	}

	public java.lang.String getCustomerNo() {
		return get("customerNo");
	}

	public void setSaleDateTime(java.util.Date saleDateTime) {
		set("saleDateTime", saleDateTime);
	}

	public java.util.Date getSaleDateTime() {
		return get("saleDateTime");
	}

	public void setTotal(java.math.BigDecimal total) {
		set("total", total);
	}

	public java.math.BigDecimal getTotal() {
		return get("total");
	}

	public void setOperatorId(java.lang.Long operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.Long getOperatorId() {
		return get("operatorId");
	}

	public void setShopId(java.lang.Long shopId) {
		set("shopId", shopId);
	}

	public java.lang.Long getShopId() {
		return get("shopId");
	}

}
